# Site settings
title: EverythingMe Engineering Blog
email: system@everything.me
description: "The EverythingMe engineers' playground. Stuff we like, stuff we work on, stuff we think, engines we rev. You know, kids stuff!"
keywords: "everythingme, launcher, engineering, android, python, go"
url: "http://geeks.everything.me" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

